spring:
  application:
    name: user-service
  rabbitmq:
    host: 192.168.32.132
    port: 5672
    username: admin
    password: admin
server:
  port: 8101

sp:
  user-service:
    user: "[{\"id\":1,\"username\":\"321\",\"password\":\"321\"},{\"id\":7,\"username\":\"abc\",\"password\":\"123\"},{\"id\":8,\"username\":\"def\",\"password\":\"456\"},{\"id\":9,\"username\":\"ghi\",\"password\":\"789\"}]"

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh